// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcService.proto

package com.wuda.raft.grpc.codegen;

public interface AppendEntryResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wuda.raft.grpc.codegen.AppendEntryResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 term = 1;</code>
   */
  long getTerm();

  /**
   * <code>bool success = 2;</code>
   */
  boolean getSuccess();
}
