// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcService.proto

package com.wuda.raft.grpc.codegen;

public interface AppendEntryParameterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wuda.raft.grpc.codegen.AppendEntryParameter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 term = 1;</code>
   */
  long getTerm();

  /**
   * <code>string leaderId = 2;</code>
   */
  java.lang.String getLeaderId();
  /**
   * <code>string leaderId = 2;</code>
   */
  com.google.protobuf.ByteString
      getLeaderIdBytes();

  /**
   * <code>bytes entries = 3;</code>
   */
  com.google.protobuf.ByteString getEntries();
}
