// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcService.proto

package com.wuda.raft.grpc.codegen;

/**
 * Protobuf type {@code com.wuda.raft.grpc.codegen.RequestVoteResult}
 */
public  final class RequestVoteResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.wuda.raft.grpc.codegen.RequestVoteResult)
    RequestVoteResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestVoteResult.newBuilder() to construct.
  private RequestVoteResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestVoteResult() {
    bambooId_ = "";
    term_ = 0L;
    voteGranted_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestVoteResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            bambooId_ = s;
            break;
          }
          case 16: {

            term_ = input.readInt64();
            break;
          }
          case 24: {

            voteGranted_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wuda.raft.grpc.codegen.RpcServiceOuterClass.internal_static_com_wuda_raft_grpc_codegen_RequestVoteResult_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wuda.raft.grpc.codegen.RpcServiceOuterClass.internal_static_com_wuda_raft_grpc_codegen_RequestVoteResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wuda.raft.grpc.codegen.RequestVoteResult.class, com.wuda.raft.grpc.codegen.RequestVoteResult.Builder.class);
  }

  public static final int BAMBOOID_FIELD_NUMBER = 1;
  private volatile java.lang.Object bambooId_;
  /**
   * <code>string bambooId = 1;</code>
   */
  public java.lang.String getBambooId() {
    java.lang.Object ref = bambooId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bambooId_ = s;
      return s;
    }
  }
  /**
   * <code>string bambooId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getBambooIdBytes() {
    java.lang.Object ref = bambooId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bambooId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TERM_FIELD_NUMBER = 2;
  private long term_;
  /**
   * <code>int64 term = 2;</code>
   */
  public long getTerm() {
    return term_;
  }

  public static final int VOTEGRANTED_FIELD_NUMBER = 3;
  private boolean voteGranted_;
  /**
   * <code>bool voteGranted = 3;</code>
   */
  public boolean getVoteGranted() {
    return voteGranted_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBambooIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, bambooId_);
    }
    if (term_ != 0L) {
      output.writeInt64(2, term_);
    }
    if (voteGranted_ != false) {
      output.writeBool(3, voteGranted_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBambooIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, bambooId_);
    }
    if (term_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, term_);
    }
    if (voteGranted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, voteGranted_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wuda.raft.grpc.codegen.RequestVoteResult)) {
      return super.equals(obj);
    }
    com.wuda.raft.grpc.codegen.RequestVoteResult other = (com.wuda.raft.grpc.codegen.RequestVoteResult) obj;

    boolean result = true;
    result = result && getBambooId()
        .equals(other.getBambooId());
    result = result && (getTerm()
        == other.getTerm());
    result = result && (getVoteGranted()
        == other.getVoteGranted());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BAMBOOID_FIELD_NUMBER;
    hash = (53 * hash) + getBambooId().hashCode();
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTerm());
    hash = (37 * hash) + VOTEGRANTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getVoteGranted());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wuda.raft.grpc.codegen.RequestVoteResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wuda.raft.grpc.codegen.RequestVoteResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.wuda.raft.grpc.codegen.RequestVoteResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.wuda.raft.grpc.codegen.RequestVoteResult)
      com.wuda.raft.grpc.codegen.RequestVoteResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wuda.raft.grpc.codegen.RpcServiceOuterClass.internal_static_com_wuda_raft_grpc_codegen_RequestVoteResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wuda.raft.grpc.codegen.RpcServiceOuterClass.internal_static_com_wuda_raft_grpc_codegen_RequestVoteResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wuda.raft.grpc.codegen.RequestVoteResult.class, com.wuda.raft.grpc.codegen.RequestVoteResult.Builder.class);
    }

    // Construct using com.wuda.raft.grpc.codegen.RequestVoteResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      bambooId_ = "";

      term_ = 0L;

      voteGranted_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wuda.raft.grpc.codegen.RpcServiceOuterClass.internal_static_com_wuda_raft_grpc_codegen_RequestVoteResult_descriptor;
    }

    public com.wuda.raft.grpc.codegen.RequestVoteResult getDefaultInstanceForType() {
      return com.wuda.raft.grpc.codegen.RequestVoteResult.getDefaultInstance();
    }

    public com.wuda.raft.grpc.codegen.RequestVoteResult build() {
      com.wuda.raft.grpc.codegen.RequestVoteResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.wuda.raft.grpc.codegen.RequestVoteResult buildPartial() {
      com.wuda.raft.grpc.codegen.RequestVoteResult result = new com.wuda.raft.grpc.codegen.RequestVoteResult(this);
      result.bambooId_ = bambooId_;
      result.term_ = term_;
      result.voteGranted_ = voteGranted_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wuda.raft.grpc.codegen.RequestVoteResult) {
        return mergeFrom((com.wuda.raft.grpc.codegen.RequestVoteResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wuda.raft.grpc.codegen.RequestVoteResult other) {
      if (other == com.wuda.raft.grpc.codegen.RequestVoteResult.getDefaultInstance()) return this;
      if (!other.getBambooId().isEmpty()) {
        bambooId_ = other.bambooId_;
        onChanged();
      }
      if (other.getTerm() != 0L) {
        setTerm(other.getTerm());
      }
      if (other.getVoteGranted() != false) {
        setVoteGranted(other.getVoteGranted());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wuda.raft.grpc.codegen.RequestVoteResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wuda.raft.grpc.codegen.RequestVoteResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object bambooId_ = "";
    /**
     * <code>string bambooId = 1;</code>
     */
    public java.lang.String getBambooId() {
      java.lang.Object ref = bambooId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bambooId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bambooId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBambooIdBytes() {
      java.lang.Object ref = bambooId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bambooId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bambooId = 1;</code>
     */
    public Builder setBambooId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bambooId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string bambooId = 1;</code>
     */
    public Builder clearBambooId() {
      
      bambooId_ = getDefaultInstance().getBambooId();
      onChanged();
      return this;
    }
    /**
     * <code>string bambooId = 1;</code>
     */
    public Builder setBambooIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bambooId_ = value;
      onChanged();
      return this;
    }

    private long term_ ;
    /**
     * <code>int64 term = 2;</code>
     */
    public long getTerm() {
      return term_;
    }
    /**
     * <code>int64 term = 2;</code>
     */
    public Builder setTerm(long value) {
      
      term_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 term = 2;</code>
     */
    public Builder clearTerm() {
      
      term_ = 0L;
      onChanged();
      return this;
    }

    private boolean voteGranted_ ;
    /**
     * <code>bool voteGranted = 3;</code>
     */
    public boolean getVoteGranted() {
      return voteGranted_;
    }
    /**
     * <code>bool voteGranted = 3;</code>
     */
    public Builder setVoteGranted(boolean value) {
      
      voteGranted_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool voteGranted = 3;</code>
     */
    public Builder clearVoteGranted() {
      
      voteGranted_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.wuda.raft.grpc.codegen.RequestVoteResult)
  }

  // @@protoc_insertion_point(class_scope:com.wuda.raft.grpc.codegen.RequestVoteResult)
  private static final com.wuda.raft.grpc.codegen.RequestVoteResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wuda.raft.grpc.codegen.RequestVoteResult();
  }

  public static com.wuda.raft.grpc.codegen.RequestVoteResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestVoteResult>
      PARSER = new com.google.protobuf.AbstractParser<RequestVoteResult>() {
    public RequestVoteResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestVoteResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestVoteResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestVoteResult> getParserForType() {
    return PARSER;
  }

  public com.wuda.raft.grpc.codegen.RequestVoteResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

