// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcService.proto

package com.wuda.raft.grpc.codegen;

/**
 * Protobuf type {@code com.wuda.raft.grpc.codegen.RequestVoteParameter}
 */
public  final class RequestVoteParameter extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.wuda.raft.grpc.codegen.RequestVoteParameter)
    RequestVoteParameterOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestVoteParameter.newBuilder() to construct.
  private RequestVoteParameter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestVoteParameter() {
    candidateTerm_ = 0L;
    candidateId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestVoteParameter(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            candidateTerm_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            candidateId_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wuda.raft.grpc.codegen.RpcServiceOuterClass.internal_static_com_wuda_raft_grpc_codegen_RequestVoteParameter_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wuda.raft.grpc.codegen.RpcServiceOuterClass.internal_static_com_wuda_raft_grpc_codegen_RequestVoteParameter_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wuda.raft.grpc.codegen.RequestVoteParameter.class, com.wuda.raft.grpc.codegen.RequestVoteParameter.Builder.class);
  }

  public static final int CANDIDATETERM_FIELD_NUMBER = 1;
  private long candidateTerm_;
  /**
   * <code>int64 candidateTerm = 1;</code>
   */
  public long getCandidateTerm() {
    return candidateTerm_;
  }

  public static final int CANDIDATEID_FIELD_NUMBER = 2;
  private volatile java.lang.Object candidateId_;
  /**
   * <code>string candidateId = 2;</code>
   */
  public java.lang.String getCandidateId() {
    java.lang.Object ref = candidateId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      candidateId_ = s;
      return s;
    }
  }
  /**
   * <code>string candidateId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCandidateIdBytes() {
    java.lang.Object ref = candidateId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      candidateId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (candidateTerm_ != 0L) {
      output.writeInt64(1, candidateTerm_);
    }
    if (!getCandidateIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, candidateId_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (candidateTerm_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, candidateTerm_);
    }
    if (!getCandidateIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, candidateId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wuda.raft.grpc.codegen.RequestVoteParameter)) {
      return super.equals(obj);
    }
    com.wuda.raft.grpc.codegen.RequestVoteParameter other = (com.wuda.raft.grpc.codegen.RequestVoteParameter) obj;

    boolean result = true;
    result = result && (getCandidateTerm()
        == other.getCandidateTerm());
    result = result && getCandidateId()
        .equals(other.getCandidateId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CANDIDATETERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCandidateTerm());
    hash = (37 * hash) + CANDIDATEID_FIELD_NUMBER;
    hash = (53 * hash) + getCandidateId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wuda.raft.grpc.codegen.RequestVoteParameter parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteParameter parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteParameter parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteParameter parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteParameter parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteParameter parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteParameter parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteParameter parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteParameter parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteParameter parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteParameter parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wuda.raft.grpc.codegen.RequestVoteParameter parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wuda.raft.grpc.codegen.RequestVoteParameter prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.wuda.raft.grpc.codegen.RequestVoteParameter}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.wuda.raft.grpc.codegen.RequestVoteParameter)
      com.wuda.raft.grpc.codegen.RequestVoteParameterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wuda.raft.grpc.codegen.RpcServiceOuterClass.internal_static_com_wuda_raft_grpc_codegen_RequestVoteParameter_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wuda.raft.grpc.codegen.RpcServiceOuterClass.internal_static_com_wuda_raft_grpc_codegen_RequestVoteParameter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wuda.raft.grpc.codegen.RequestVoteParameter.class, com.wuda.raft.grpc.codegen.RequestVoteParameter.Builder.class);
    }

    // Construct using com.wuda.raft.grpc.codegen.RequestVoteParameter.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      candidateTerm_ = 0L;

      candidateId_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wuda.raft.grpc.codegen.RpcServiceOuterClass.internal_static_com_wuda_raft_grpc_codegen_RequestVoteParameter_descriptor;
    }

    public com.wuda.raft.grpc.codegen.RequestVoteParameter getDefaultInstanceForType() {
      return com.wuda.raft.grpc.codegen.RequestVoteParameter.getDefaultInstance();
    }

    public com.wuda.raft.grpc.codegen.RequestVoteParameter build() {
      com.wuda.raft.grpc.codegen.RequestVoteParameter result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.wuda.raft.grpc.codegen.RequestVoteParameter buildPartial() {
      com.wuda.raft.grpc.codegen.RequestVoteParameter result = new com.wuda.raft.grpc.codegen.RequestVoteParameter(this);
      result.candidateTerm_ = candidateTerm_;
      result.candidateId_ = candidateId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wuda.raft.grpc.codegen.RequestVoteParameter) {
        return mergeFrom((com.wuda.raft.grpc.codegen.RequestVoteParameter)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wuda.raft.grpc.codegen.RequestVoteParameter other) {
      if (other == com.wuda.raft.grpc.codegen.RequestVoteParameter.getDefaultInstance()) return this;
      if (other.getCandidateTerm() != 0L) {
        setCandidateTerm(other.getCandidateTerm());
      }
      if (!other.getCandidateId().isEmpty()) {
        candidateId_ = other.candidateId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wuda.raft.grpc.codegen.RequestVoteParameter parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wuda.raft.grpc.codegen.RequestVoteParameter) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long candidateTerm_ ;
    /**
     * <code>int64 candidateTerm = 1;</code>
     */
    public long getCandidateTerm() {
      return candidateTerm_;
    }
    /**
     * <code>int64 candidateTerm = 1;</code>
     */
    public Builder setCandidateTerm(long value) {
      
      candidateTerm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 candidateTerm = 1;</code>
     */
    public Builder clearCandidateTerm() {
      
      candidateTerm_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object candidateId_ = "";
    /**
     * <code>string candidateId = 2;</code>
     */
    public java.lang.String getCandidateId() {
      java.lang.Object ref = candidateId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        candidateId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string candidateId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCandidateIdBytes() {
      java.lang.Object ref = candidateId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        candidateId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string candidateId = 2;</code>
     */
    public Builder setCandidateId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      candidateId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string candidateId = 2;</code>
     */
    public Builder clearCandidateId() {
      
      candidateId_ = getDefaultInstance().getCandidateId();
      onChanged();
      return this;
    }
    /**
     * <code>string candidateId = 2;</code>
     */
    public Builder setCandidateIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      candidateId_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.wuda.raft.grpc.codegen.RequestVoteParameter)
  }

  // @@protoc_insertion_point(class_scope:com.wuda.raft.grpc.codegen.RequestVoteParameter)
  private static final com.wuda.raft.grpc.codegen.RequestVoteParameter DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wuda.raft.grpc.codegen.RequestVoteParameter();
  }

  public static com.wuda.raft.grpc.codegen.RequestVoteParameter getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestVoteParameter>
      PARSER = new com.google.protobuf.AbstractParser<RequestVoteParameter>() {
    public RequestVoteParameter parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestVoteParameter(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestVoteParameter> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestVoteParameter> getParserForType() {
    return PARSER;
  }

  public com.wuda.raft.grpc.codegen.RequestVoteParameter getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

