// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcService.proto

package com.wuda.raft.grpc.codegen;

public interface RequestVoteResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wuda.raft.grpc.codegen.RequestVoteResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bambooId = 1;</code>
   */
  java.lang.String getBambooId();
  /**
   * <code>string bambooId = 1;</code>
   */
  com.google.protobuf.ByteString
      getBambooIdBytes();

  /**
   * <code>int64 term = 2;</code>
   */
  long getTerm();

  /**
   * <code>bool voteGranted = 3;</code>
   */
  boolean getVoteGranted();
}
