// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcService.proto

package com.wuda.raft.grpc.codegen;

public interface RequestVoteParameterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wuda.raft.grpc.codegen.RequestVoteParameter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 candidateTerm = 1;</code>
   */
  long getCandidateTerm();

  /**
   * <code>string candidateId = 2;</code>
   */
  java.lang.String getCandidateId();
  /**
   * <code>string candidateId = 2;</code>
   */
  com.google.protobuf.ByteString
      getCandidateIdBytes();
}
