// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcService.proto

package com.wuda.raft.grpc.codegen;

public final class RpcServiceOuterClass {
  private RpcServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuda_raft_grpc_codegen_RequestVoteParameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuda_raft_grpc_codegen_RequestVoteParameter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuda_raft_grpc_codegen_RequestVoteResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuda_raft_grpc_codegen_RequestVoteResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuda_raft_grpc_codegen_AppendEntryParameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuda_raft_grpc_codegen_AppendEntryParameter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuda_raft_grpc_codegen_AppendEntryResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuda_raft_grpc_codegen_AppendEntryResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020RpcService.proto\022\032com.wuda.raft.grpc.c" +
      "odegen\"B\n\024RequestVoteParameter\022\025\n\rcandid" +
      "ateTerm\030\001 \001(\003\022\023\n\013candidateId\030\002 \001(\t\"H\n\021Re" +
      "questVoteResult\022\020\n\010bambooId\030\001 \001(\t\022\014\n\004ter" +
      "m\030\002 \001(\003\022\023\n\013voteGranted\030\003 \001(\010\"G\n\024AppendEn" +
      "tryParameter\022\014\n\004term\030\001 \001(\003\022\020\n\010leaderId\030\002" +
      " \001(\t\022\017\n\007entries\030\003 \001(\014\"2\n\021AppendEntryResu" +
      "lt\022\014\n\004term\030\001 \001(\003\022\017\n\007success\030\002 \001(\0102\361\001\n\nRp" +
      "cService\022n\n\013requestVote\0220.com.wuda.raft." +
      "grpc.codegen.RequestVoteParameter\032-.com." +
      "wuda.raft.grpc.codegen.RequestVoteResult" +
      "\022s\n\020appendEntriesRpc\0220.com.wuda.raft.grp" +
      "c.codegen.AppendEntryParameter\032-.com.wud" +
      "a.raft.grpc.codegen.AppendEntryResultB\002P" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_wuda_raft_grpc_codegen_RequestVoteParameter_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_wuda_raft_grpc_codegen_RequestVoteParameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuda_raft_grpc_codegen_RequestVoteParameter_descriptor,
        new java.lang.String[] { "CandidateTerm", "CandidateId", });
    internal_static_com_wuda_raft_grpc_codegen_RequestVoteResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_wuda_raft_grpc_codegen_RequestVoteResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuda_raft_grpc_codegen_RequestVoteResult_descriptor,
        new java.lang.String[] { "BambooId", "Term", "VoteGranted", });
    internal_static_com_wuda_raft_grpc_codegen_AppendEntryParameter_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_wuda_raft_grpc_codegen_AppendEntryParameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuda_raft_grpc_codegen_AppendEntryParameter_descriptor,
        new java.lang.String[] { "Term", "LeaderId", "Entries", });
    internal_static_com_wuda_raft_grpc_codegen_AppendEntryResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_wuda_raft_grpc_codegen_AppendEntryResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuda_raft_grpc_codegen_AppendEntryResult_descriptor,
        new java.lang.String[] { "Term", "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
